"""Constantes de dominio."""

DEFAULT_CATEGORY_NAME = "Sin categoria"
MOVEMENT_STATUS_ACTIVE = "ACTIVO"
MOVEMENT_STATUS_IGNORED = "IGNORADO"
MOVEMENT_STATUS_DELETED = "BORRADO"
MOVEMENT_TYPE_EXPENSE = "GASTO"
MOVEMENT_TYPE_INCOME = "INGRESO"
MOVEMENT_TYPE_NEUTRAL = "NEUTRO"
