[theme]
base = "light"
primaryColor = "#0A0A0A"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A0A"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
